[.intro]
== Legacy Code

====
How to modernize a legacy component with the CDI Programming Model
====


[.topic.source]
== A legacy component

TIP: Transformation engine used at Murex to transform message formats from external systems into Murex canonical format

[plantuml, "legacy", "svg", width="100%", height="75%"]
----
@startuml
scale 600 width
scale 400 height

skinparam shadowing false
skinparam backgroundColor transparent
skinparam defaultFontName "Courier New", Courier, monospace

skinparam class {
  BackgroundColor #337788
  ArrowColor #888888
  BarColor #888888
  BorderColor White
  FontName "Courier New", Courier, monospace
  FontColor White
  FontSize 20
  AttributeFontColor White
}

interface Executor {
    + DataDictionaryFormulaResult executeFormula(String, SDDParameterProvider)
    + byte[] executeTemplate(String, SDDParameterProvider)
    + void close()
}
note top of Executor: Transformation Engine

abstract class AbstractExecutor {
    + DataDictionaryFormulaResult executeFormula(String, SDDParameterProvider)
    + byte[] executeTemplate(String, SDDParameterProvider)
    + CacheConfig createCacheFromFile(String)
    + ManageableCache getCache(String)
    + void removeFromDictionaryCaches(Set<String>)
    + void close()
}
Executor <|.. AbstractExecutor

class OfflineExecutor {
    + OfflineExecutor(ResourceLoader, BoRepositoryService, String, String, String)
    + OfflineExecutor(ResourceLoader, BoRepositoryService, String, String, String, ClassLoader)
    __
    + void setContextClassLoader(ClassLoader)
    + setOverridenResource(Object)
}
AbstractExecutor <|-- OfflineExecutor

interface ResourceLoader {
    + Version getVersion()
    + List<DDOFormula> readFormulae()
    + List<DDOSkeleton> readSkeletons()
    + List<DDOContext> readContexts()
    + List<DDOTemplate> readTemplates()
    + DDOFormula readFormula(String)
    + DDOSkeleton readSkeleton(String)
    + DDOContext readContext(String)
    + DDOTemplate readTemplate(String)
    + DDOTemplate readTemplate(String, String)
    + boolean isFormulaExists(String)
    + int getType()
    + String getLocation()
    + void cleanUp()
    + byte[] getClazz(String)
    + byte[] getJavaClass(String)
}
note top of ResourceLoader: Transformation Configuration / Logic
OfflineExecutor -left-> ResourceLoader

class SDDParameterProvider {
    + String getExtractionFormula()
    + void setExtractionFormula(String)
    + boolean isEmpty()
    + SDDParameterProvider clone()
    + setMxObject(Object)
    + updateWithXmlEntry(XmlEntry)
    + Set<String> getContexts()
    + Map<String, Object> getFields()
}
note top of SDDParameterProvider: Transformation Input Model
Executor -left- SDDParameterProvider : input >

abstract Class AbstractParameterProvider {
    + Map<String, Object> getFields()
    + Map<String, Object> getParameters()
    + TraceableDocument getDocument(String)
    + Object getField(String)
    + Object getParameter(String)
    + String getLocalParameter(String)
    + String getGlobalParameter(String)
    + Map<String, TraceableDocument> getDocuments()
    + Object getBO()
    + Serializable getKey(String)
}
SDDParameterProvider -down-|> AbstractParameterProvider

class DataDictionaryFormulaResult {
    + String getFormulaReturnTypeAsString(int)
    + int getFormulaReturnTypeAsInt(int)
    + void cleanUp()
    + void createObject(int, int)
    + int getLineCount()
    + int getColumnCount()
    + Object getObjectValue(int, int)
    + String getValue(int, int)
    + void createObject(Element)
    + void createObject(SAXSerializable)
    + void createObject(DataDictionaryFormulaResultCell[][])
    + void setColumnTitles(String [])
    + boolean isTreeResult()
    + boolean isObjectResult()
    + void setValueAt(int, int, DataDictionaryFormulaResultCell[][])
    + void setColumnTitleAt(int, String)
    + Object[][] getObjectResult()
}
note top of DataDictionaryFormulaResult: Transformation Output Model / Type Conversion
Executor -- DataDictionaryFormulaResult : output >

@enduml
----


[.topic.source]
== Legacy component out of the box (without CDI)

[source, subs="verbatim,quotes", role="smaller"]
.Module containing the transformation logic `fpml2mxml.jar` that we want to reuse as is
----
@Formula
class Fpml2mxmlTransformation {
    public MxML transformation(FpML fpml) { /* transformation logic */ }
}
----

[source, subs="verbatim,quotes", role="smaller"]
.The tranformation engine that uses that module
----
class FpmlToMxmlTransformationMain throws Exception {
    public static void main(String[] args) {
        FpML inputFpml = (FpML) JAXBContext.newInstance(FpML.class)
            .createUnmarshaller().unmarshal(new File("fpml.xml"));
        MultiReader reader = new MultiReader(Collections.emptyList(),
            Arrays.asList("fpml2mxml.jar"));
        [highlight]#Executor executor = new Executor(reader, null, "", "", "",
            FpmlToMxmlTransformationMain.class.getClassLoader(), true);#
        SDDParameterProvider parameters = new SDDParameterProvider(new Properties());
        parameters.setObject(inputFpml);
        DataDictionaryFormulaResult result = executor.executeFormula("Fpml2mxmlTransformation", parameters);
        Mxml outputMxml = (Mxml) result.getObjectValue(0, 0);
        executor.cleanUp();
    }
}
----


[.topic.source]
== Modernize the legacy component API with CDI

[.statement]
====

TIP: We want the end-user to write that code instead to achieve the same result:

[source, subs="verbatim,quotes"]
----
@Inject
@Formula(name = "Fpml2mxmlTransformation", path = "fpml2mxml.jar")
Transformer<FpML, MxML> transformer;

FpML input = (FpML) JAXBContext.newInstance(FpML.class)
                               .createUnmarshaller()
                               .unmarshal(new File("fpml.xml"));

Mxml result = transformer.transform(input);
----
====


[.topic.source]
== Our goals

[.statement]
====

icon:lightbulb-o[] Define a facade for the legacy component that's functional and typesafe

icon:lightbulb-o[] Hide the technical code that manages the configuration and the lifecycle of the legacy component

icon:ban[] _Without touching the component source / binary because we don't own it_
====


[.topic.source]
== How to achieve this?

TIP: We need to write an extension that will:

. Collect the configuration metadata, i.e. the `@Formula(...)`, required to instantiate the legacy component by observing the `ProcessInjectionPoint` lifecycle event
. Declare the legacy component as a CDI bean programmatically by implementing the `Bean` SPI and observing the `AfterBeanDiscovery` lifecycle event
. Declare a producer method that will produce the `Transformer` facade instances and use the legacy component CDI bean


[.topic.source]
== So we will `@Observes` these 2 events to add our features

[plantuml, "lifecycle-PIP-ABD", "svg", height="85%", width="95%"]
----
@startuml

skinparam shadowing false
skinparam backgroundColor transparent
skinparam defaultFontName "Courier New", Courier, monospace

skinparam activity {
  FontSize 20
  FontName "Courier New", Courier, monospace
  FontColor #337788
  ArrowColor #888888
  BorderColor #337788
  BackgroundColor #white

  FontColor<< Internal >> #888888
  BorderColor<< Internal >> #888888
  BackgroundColor<< Internal >> #white

  FontColor<< Once >> #BB3322
  BorderColor<< Once >> #BB3322
  BackgroundColor<< Once >> #white

  FontColor<< Highlight >> white
  BorderColor<< Highlight >> #337788
  BackgroundColor<< Highlight >> #337788

  FontColor<< HighlightOnce >> white
  BorderColor<< HighlightOnce >> #BB3322
  BackgroundColor<< HighlightOnce >> #BB3322
}

(*) -right-> "Deployment\nStart" << Internal >>
-right-> "Before\nBean\nDiscovery" << Once >>
-right-> "Scan\nArchive" << Internal >>
-right-> "Process\nAnnotated\nType"
-right-> "After\nType\nDiscovery" << Once >>
-down-> "Bean\nEligibility\nCheck" << Internal >>
-left-> "Process\nInjection\nPoint" << Highlight >>
-left-> "Process\nInjection\nTarget"
-left-> "Process\nBean\nAttributes"
-down-> "Process\nBean"
-right-> "Process\nProducer"
-right-> "Process\nObserver\nMethod"
-right-> "After\nBean\nDiscovery" << HighlightOnce >>
-down-> "After\nDeployment\nValidation" << Once >>
-left-> "Application\nRunning" << Internal >>
-left-> "Before\nShutdown" << Once >>
-left-> "Undeploy\nApplication" << Internal >>
-left-> (*)

@enduml
----

include::legend.adoc[]


[.topic.source]
== First goal: Define a facade for the legacy component

TIP: Define a functional interface:

[source, subs="verbatim,quotes", role="smaller"]
----
public interface Transformer<I, O> {
    O transform(I input);
}
----

TIP: And a CDI qualifier with configuration metadata:

[source, subs="verbatim,quotes", role="smaller"]
----
import javax.enterprise.util.Nonbinding;
import javax.inject.Qualifier;
[highlight]#@Qualifier#
public @interface Formula {
    [highlight]#@Nonbinding#
    String name() default ""; // The tranformation name
    [highlight]#@Nonbinding#
    String path() default ""; // The tranformation module
}
----


[.topic.source]
== Configuration at injection points

TIP: Distribute configuration closer to the code:

[source, subs="verbatim,quotes"]
----
@Inject
[highlight]#@Formula(name = "Fpml2mxmlTransformation", path = "fpml2mxml.jar")#
Transformer<FpML, MxML> fpmlToMxmlTransformer;

...

@Inject
[highlight]#@Formula(name = "Fixml2mxmlTransformation", path = "fixml2mxml.jar")#
Transformer<FixML, MxML> fixmlToMxmlTransformer;

...
----


[.topic.source]
== Second goal: Hide the technical code

TIP: We first need to collect all the `@Formula` pathes metadata required to instantiate the legacy component to get rid of the following code

[source, subs="verbatim,quotes", role="smaller"]
----
MultiReader reader = new MultiReader(Collections.emptyList(), Arrays.asList("fpml2mxml.jar", "fixml2mxml.jar"));
----

TIP: By observing the `ProcessInjectionPoint` lifecycle event

[source, subs="verbatim,quotes"]
----
public interface ProcessInjectionPoint<T, X> {
    [highlight]#public InjectionPoint getInjectionPoint();#
    public void setInjectionPoint(InjectionPoint injectionPoint);
    public void addDefinitionError(Throwable t);
}
----


[.topic.source]
== Collect the legacy component configuration

TIP: In a CDI extension

[source, subs="verbatim,quotes"]
----
class LegacyComponentExtension implements Extension {

  final List<String> pathes = new ArrayList<>();

  void collectPathes(@Observes [highlight]#ProcessInjectionPoint<?, Transformer># pit) { <1>
    Annotated annotated = pit.getInjectionPoint().getAnnotated();
    if (annotated.isAnnotationPresent([highlight]#Formula.class#))
        pathes.add(annotated.getAnnotation(Formula.class).path()); <2>
  }
}
----
<1> Observe every injection point of type `Transformer` on any declaring bean
<2> Collect the injection point `@Formula` `path` attribute


[.topic.source]
== Declaring the legacy component as a CDI bean programmatically

icon:question-circle[] Why do we need to add a bean programmatically?

icon:info-circle[] The legacy component is not a bean archive:

. It does not contain a `beans.xml` (explicit bean archive)
. Nor it contains one or more bean classes with a bean defining annotation (implicit bean archive)

icon:ban[] We cannot touch the component source / binary because we don't own it


[.topic.source]
== The `Bean SPI`

icon:question-circle[] So how to declare a bean programmatically?

TIP: We need to implement the `Bean` SPI

[source]
----
public interface Bean<T> extends Contextual<T>, BeanAttributes<T> {
    Class<?> getBeanClass();
    Set<InjectionPoint> getInjectionPoints();
    T create(CreationalContext<T> creationalContext); // Contextual<T>
    void destroy(T instance, CreationalContext<T> creationalContext);
    Set<Type> getTypes(); // BeanAttributes<T>
    Set<Annotation> getQualifiers();
    Class<? extends Annotation> getScope();
    String getName();
    Set<Class<? extends Annotation>> getStereotypes();
    boolean isAlternative();
}
----


[.topic.source]
== Implementing the `Bean` SPI

[source, subs="verbatim,quotes", role="smaller"]
----
class LegacyExecutorBean implements Bean<Executor> {
    private final Set<Annotation> qualifiers = new HashSet<>(Arrays.asList(new AnnotationLiteral<Any>(){},
                                                                       new AnnotationLiteral<Default>(){}));
    List<String> pathes = new ArrayList<>();
    LegacyExecutorBean(List<String> pathes) {
        this.pathes = pathes;
    }
    public Class<? extends Annotation> getScope() {
        return ApplicationScoped.class;
    }
    public Set<Annotation> getQualifiers() {
        return Collections.unmodifiableSet(qualifiers);
    }
    public Set<Type> getTypes() {
        return Collections.singleton(Executor.class);
    }
    public Executor create(CreationalContext<Executor> creational) {
        MultiReader reader = new MultiReader(Collections.emptyList(), pathes);
        return new Executor(reader, null, "", "", "", Executor.class.getClassLoader(), true);
    }
    public void destroy(Executor instance, CreationalContext<Executor> creational) {
        executor.cleanUp();
    }
    //...
----


[.topic.source]
== Implementing the `Bean` SPI (continued)

[source, subs="verbatim,quotes", role="smaller"]
----
    //...
    public Class<?> getBeanClass() {
        return Executor.class;
    }
    public Set<InjectionPoint> getInjectionPoints() {
        return Collections.emptySet();
    }
    public String getName() { // Only called for @Named bean
        return "";
    }
    public Set<Class<? extends Annotation>> getStereotypes() {
        return Collections.emptySet();
    }
    public boolean isAlternative() {
        return false;
    }
    public boolean isNullable() { // Deprecated since CDI 1.1
        return false;
    }
}
----


[.topic.source]
== Adding a programmatic bean to the deployment

icon:question-circle[] Then, how to add a bean declared programmatically?

TIP: By observing the `AfterBeanDiscovery` lifecycle event

[source, subs="verbatim,quotes"]
----
public interface AfterBeanDiscovery {
    void addDefinitionError(Throwable t);
    [highlight]#void addBean(Bean<?> bean);#
    void addObserverMethod(ObserverMethod<?> observerMethod);
    void addContext(Context context);
    <T> AnnotatedType<T> getAnnotatedType(Class<T> type, String id);
    <T> Iterable<AnnotatedType<T>> getAnnotatedTypes(Class<T> type);
}
----


[.topic.source]
== Adding the legacy component bean

TIP: In the CDI extension...

[source, subs="verbatim,quotes"]
----
class LegacyComponentExtension implements Extension {

    final List<String> pathes = new ArrayList<>();

    void collectPathes(@Observes ProcessInjectionPoint<?, Transformer> pit) {
        Annotated annotated = pit.getInjectionPoint().getAnnotated();
        if (annotated.isAnnotationPresent(Formula.class))
            pathes.add(annotated.getAnnotation(Formula.class).path());
    }

    void addLegacyComponentBean(@Observes [highlight]#AfterBeanDiscovery# abd) {
        abd.[highlight]#addBean(new LegacyExecutorBean(pathes))#;
    }
}
----


[.topic.source]
== Declare the `Transformer` facade

TIP: Finally we declare a producer method for the `Transformer` facade that uses the `InjectionPoint` API

[source, subs="verbatim,quotes", role="smaller"]
----
[highlight]#@Produces# [highlight]#@Formula#
[highlight]#<I, O> Transformer<I, O># produceTransformer([highlight]#Executor executor#, [highlight]#InjectionPoint ip#) {
    final String formula = ip.getAnnotated().getAnnotation(Formula.class).name();
    return new Transformer<I, O>() {
        public O transform(I input) {
            SDDParameterProvider parameters = new SDDParameterProvider(new Properties());
            parameters.setObject(input);
            DataDictionaryFormulaResult result = executor.executeFormula(formula, parameters);
            return (O) result.getObjectValue(0, 0);
        }
    };
}
----

TIP: *Parameterized types are not erased by CDI* and accessible from `InjectionPoint.getType()`, so that they can be used as metadata as well. For example for _type check_ / _conversion_.


[.topic]
== Second goal achieved

[.statement]
====
TIP: We can get rid of the following technical code

[source, subs="verbatim,quotes", role="smaller"]
----
FpML inputFpml = (FpML) JAXBContext.newInstance(FpML.class)
                 .createUnmarshaller().unmarshal(new File("fpml.xml"));
[highlight]#MultiReader reader = new MultiReader(Collections.emptyList(), Arrays.asList("fpml2mxml.jar"));
Executor executor = new Executor(reader, null, "", "", "", Executor.class.getClassLoader(), true);
SDDParameterProvider parameters = new SDDParameterProvider(new Properties());
parameters.setObject(inputFpml);
DataDictionaryFormulaResult result = executor.executeFormula("Fpml2mxmlTransformation", parameters);
Mxml outputMxml = (Mxml) result.getObjectValue(0, 0);
executor.cleanUp();#
}
----

TIP: And write instead:

[source, subs="verbatim,quotes", role="smaller"]
----
@Inject
@Formula(name = "Fpml2mxmlTransformation", path = "fpml2mxml.jar")
Transformer<FpML, MxML> transformer;
Mxml result = transformer.transform(inputFpml);
----

====
