[.topic.intro]
== Metrics CDI

====
Integrate a Third-party Library into the CDI Programming Model
====


[.topic.source]
== Dropwizard Metrics

NOTE: Open-source Java library providing monitoring primitives like `Counter`, `Gauge`, `Histogram`, `Meter`, `Timer`, ...

NOTE: Provides a `MetricRegistry` that articulates application / module metrics and metrics reporters

NOTE: Defines annotations for AOP frameworks like Spring AOP, AspectJ, Guice (AOP Alliance) *and CDI*: `@Counted`, `@ExceptionMetered`, `@Metered`, `@Timed`, ...


[.topic.recap]
== `Timer` Example

[source, subs="verbatim,quotes"]
----
class MetricRegistryBean {
    @Produces @ApplicationScoped
    MetricRegistry registry = new MetricRegistry();
}
----

[source, subs="verbatim,quotes"]
----
class TimedMethodBean {
    @Inject MetricRegistry registry;

    void timedMethod() {
        Timer timer = registry.timer("timer");
        Timer.Context time = timer.time();
        try {
            // method logic
        } finally {
            time.stop();
        }
    }
}
----


[.topic.recap]
== Further CDI

TIP: Encapsulate the `Timer` retrieval and timing logic

[source, subs="verbatim,quotes"]
----
import com.codahale.metrics.annotation.Timed;

class TimedMethodBean {

    [highlight]#@Timed("timer")#
    void timedMethod() {
        // method logic
    }
}
----


[.topic.source]
== Java Interceptors and Bindings

TIP: Use *Java interceptors* for Metrics annotations AOP

[source, subs="verbatim,quotes"]
----
import javax.interceptor.Interceptor;
import javax.interceptor.InterceptorBinding;

import javax.annotation.Priority;

----

TIP: Use *Java interceptor bindings* to associate interceptors to methods

[source, subs="verbatim,quotes"]
----
[highlight]#@InterceptorBinding#
@Target({ ElementType.TYPE, ElementType.METHOD })
@Retention(RetentionPolicy.RUNTIME)
@interface TimedBinding {
}
----


[.topic.source]
== `AroundInvoke` Interceptor

[source, subs="verbatim,quotes"]
----
@Interceptor
[highlight]#@TimedBinding#
@Priority(Interceptor.Priority.LIBRARY_BEFORE)
class TimedInterceptor {
    @Inject MetricRegistry registry;

    [highlight]#@AroundInvoke#
    Object timeMethod(InvocationContext context) throws Exception {
        String name = context.getMethod().getAnnotation(Timed.class).name();
        Timer timer = registry.timer(name);
        Timer.Context time = timer.time();
        try {
            return [highlight]#context.proceed()#;
        } finally {
            time.stop();
        }
    }
}
----


[.topic.source]
== Bean Method Interceptor

CAUTION: Forces to add the binding manually :-(

[source, subs="verbatim,quotes"]
----
class TimedMethodBean {

    [highlight]#@TimedBinding#
    @Timed("timer")
    void timedMethod() {
    }
}
----


[.topic.source]
== The `ProcessAnnotatedType<X>` Event

TIP: Use the *CDI SPI* to add the interceptor binding to the annotated methods programmatically in a *CDI extension*

[source, subs="verbatim,quotes"]
----
package javax.enterprise.inject.spi;

public interface ProcessAnnotatedType<X> {
    public AnnotatedType<X> getAnnotatedType();
    public void setAnnotatedType(AnnotatedType<X> type);
    public void veto();
}
----


[.topic.source]
== `ProcessAnnotatedType` in Lifecycle

[plantuml, "lifecycle-pat", "svg", height="85%", width="95%"]
----
@startuml

skinparam shadowing false
skinparam backgroundColor transparent
skinparam defaultFontName Consolas

skinparam activity {
  FontSize 20
  FontName Consolas
  FontColor #337788
  ArrowColor #888888
  BorderColor #337788
  BackgroundColor #white

  FontColor<< Internal >> #888888
  BorderColor<< Internal >> #888888
  BackgroundColor<< Internal >> #white

  FontColor<< Once >> #BB3322
  BorderColor<< Once >> #BB3322
  BackgroundColor<< Once >> #white

  FontColor<< Highlight >> white
  BorderColor<< Highlight >> #337788
  BackgroundColor<< Highlight >> #337788
}

(*) -right-> "Deployment\nStart" << Internal >>
-right-> "Before\nBean\nDiscovery" << Once >>
-right-> "Scan\nArchive" << Internal >>
-right-> "Process\nAnnotated\nType" <<Highlight>>
-right-> "After\nType\nDiscovery" << Once >>
-down-> "Bean\nEligibility\nCheck" << Internal >>
-left-> "Process\nInjection\nPoint"
-left-> "Process\nInjection\nTarget"
-left-> "Process\nBean\nAttributes"
-down-> "Process\nBean"
-right-> "Process\nProducer"
-right-> "Process\nObserver\nMethod"
-right-> "After\nBean\nDiscovery" << Once >>
-down-> "After\nDeployment\nValidation" << Once >>
-left-> "Application\nRunning" << Internal >>
-left-> "Before\nShutdown" << Once >>
-left-> "Undeploy\nApplication" << Internal >>
-left-> (*)

@enduml
----

include::legend.adoc[]


[.topic.source]
== Add Interceptor Bindings Programmatically

[source, subs="verbatim,quotes"]
----
class MetricsExtension implements [highlight]#Extension# {

  <X> void bindTimedMethodInterceptor(@Observes [highlight]#@WithAnnotations(Timed.class)
    ProcessAnnotatedType<X># pat) { <1>
    AnnotatedTypeBuilder<X> atb = new AnnotatedTypeBuilder<>();
    atb.readFromType(pat.getAnnotatedType());
    for (AnnotatedMethod<? super X> method : pat.getAnnotatedType().getMethods())
      if (method.isAnnotationPresent(Timed.class))
        atb.addToMethod(method, [highlight]#new AnnotationLiteral<TimedBinding>(){}#)); <2>

    pat.setAnnotatedType(atb.create());
  }
}
----
<1> Observe types containing the `@Timed` annotation
<2> Add the interceptor binding to the annotated methods


[.topic.source]
== Declare an Annotation as Interceptor Binding

TIP: Alternative: use the *CDI SPI* to directly declare the `@Timed` annotation as interceptor binding

[source, subs="verbatim,quotes"]
----
class MetricsExtension implements Extension {

  <X> void addTimedBinding(@Observes [highlight]#BeforeBeanDiscovery# bbd, BeanManager manager) {
    AnnotatedTypeBuilder<X> atb = new AnnotatedTypeBuilder<>();
    atb.readFromType(manager.createAnnotatedType([highlight]#Timed.class#));
    for (Method method : Timed.class.getMethods())
        atb.addToMethod(method, new AnnotationLiteral<NonBinding>(){}); <1>

    bbd.[highlight]#addInterceptorBinding#(atb.create());
  }
}
----
<1> Declare the `@Timed` annotation attributes as `@NonBinding`


[.topic.source]
== Metrics Customization

icon:question-circle[] How to customize the metric instances

[source, subs="verbatim,quotes"]
----
@AroundInvoke
Object timedMethod(InvocationContext context) throws Exception {
    String name = context.getMethod().getAnnotation(Timed.class).name();
    [highlight]#Timer timer = registry.timer(name)#; <1>
    Timer.Context time = timer.time();
    try {
        return context.proceed();
    } finally {
        time.stop();
    }
}
----
<1> Default `Timer` histogram is exponentially biased to the past 5 minutes of measurements


[.topic.recap]
== `Timer` Example

[source, subs="verbatim,quotes"]
----
class TimedMethodBean {

    @Inject
    TimedMethodBean(MetricRegistry registry) {
      Timer timer = new Timer(
          new SlidingTimeWindowReservoir(1L, TimeUnit.MINUTES));

      if (!registry.getMetrics().containsKey("timer"))
          registry.register("timer", timer);
    }

    @Timed("timer")
    void timedMethod() {
    }
}
----


[.topic.recap]
== Further CDI

TIP: Use *producer fields / methods* to declare custom +
metrics

[source, subs="verbatim,quotes"]
----

class TimedMethodBean {

    [highlight]#@Produces#
    static Timer timer() {
        return new Timer(new SlidingTimeWindowReservoir(1L, TimeUnit.MINUTES));
    }

    @Timed("timer")
    void timedMethod() {
    }
}
----


[.topic.source]
== The `ProcessBean<X>` Events

TIP: Detect the *producer fields* and *methods* to instantiate and register the custom metrics

[source]
----
package javax.enterprise.inject.spi;

public interface ProcessProducerField<T, X> extends ProcessBean<X> {
    public AnnotatedField<T> getAnnotatedProducerField();
    public AnnotatedParameter<T> getAnnotatedDisposedParameter();
    // ProcessBean<X>
    public Annotated getAnnotated();
    public Bean<X> getBean();
}
----

NOTE: `ProcessManagedBean<X>` and `ProcessProducerMethod<T, X>` are fired for managed beans and producer methods respectively


[.topic.source]
== `ProcessBean<X>` in Lifecycle

[plantuml, "lifecycle-pb", "svg", height="85%", width="95%"]
----
@startuml

skinparam shadowing false
skinparam backgroundColor transparent
skinparam defaultFontName Consolas

skinparam activity {
  FontSize 20
  FontName Consolas
  FontColor #337788
  ArrowColor #888888
  BorderColor #337788
  BackgroundColor #white

  FontColor<< Internal >> #888888
  BorderColor<< Internal >> #888888
  BackgroundColor<< Internal >> #white

  FontColor<< Once >> #BB3322
  BorderColor<< Once >> #BB3322
  BackgroundColor<< Once >> #white

  FontColor<< Highlight >> white
  BorderColor<< Highlight >> #337788
  BackgroundColor<< Highlight >> #337788
}

(*) -right-> "Deployment\nStart" << Internal >>
-right-> "Before\nBean\nDiscovery" << Once >>
-right-> "Scan\nArchive" << Internal >>
-right-> "Process\nAnnotated\nType"
-right-> "After\nType\nDiscovery" << Once >>
-down-> "Bean\nEligibility\nCheck" << Internal >>
-left-> "Process\nInjection\nPoint"
-left-> "Process\nInjection\nTarget"
-left-> "Process\nBean\nAttributes"
-down-> "Process\nBean" <<Highlight>>
-right-> "Process\nProducer"
-right-> "Process\nObserver\nMethod"
-right-> "After\nBean\nDiscovery" << Once >>
-down-> "After\nDeployment\nValidation" << Once >>
-left-> "Application\nRunning" << Internal >>
-left-> "Before\nShutdown" << Once >>
-left-> "Undeploy\nApplication" << Internal >>
-left-> (*)

@enduml
----

include::legend.adoc[]


[.topic.source]
== The `AfterDeploymentValidation` Event

[source, subs="verbatim,quotes"]
----
class MetricsExtension implements Extension {
  Map<Bean<?>, AnnotatedMember<?>> metrics = new HashMap<>();
  void producerFields(@Observes [highlight]#ProcessProducerField<? extends Metric, ?># ppf) {
    metrics.put(ppf.getBean(), ppf.getAnnotatedProducerField()); <1>
  }
  void producerMethods(@Observes [highlight]#ProcessProducerMethod<? extends Metric, ?># ppm) {
    metrics.put(ppm.getBean(), ppm.getAnnotatedProducerMethod()); <1>
  }
  void customMetrics(@Observes [highlight]#AfterDeploymentValidation# adv, BeanManager manager) {
    for (Map.Entry<Bean<?>, AnnotatedMember<?>> metric : metrics.entrySet())
      registry.register(member.getName(), manager.getReference(metric.getKey(), <2>
        metric.getValue().getBaseType(), manager.createCreationalContext(null)));
  }
}
----
<1> Collect the custom `Metric` producer fields and methods
<2> Instantiate and register the custom metrics into the Metrics registry


[.topic.source]
== Example: Composition of Metrics

[source, subs="verbatim,quotes"]
----
@Inject
private Meter [highlight]#hits#; <1>

@Timed(name = "[highlight]#calls#") <2>
public void cachedMethod() {
    if (hit) hits.mark();
}

@Produces @Metric(name = "[highlight]#cache-hits#") <3>
private Gauge<Double> cacheHitRatioGauge(Meter [highlight]#hits#, Timer [highlight]#calls#) {
    return () -> calls.getOneMinuteRate() == 0 ? Double.NaN :
                 hits.getOneMinuteRate() / calls.getOneMinuteRate();
}
----
<1> `Metric` _injection_ from the registry
<2> Method _instrumentation_ with interceptors
<3> Produce a custom `Metric` instance by composing others
