[.topic.intro]
== Metrics CDI

====
Integrating Dropwizard Metrics in CDI
====


[.topic.source]
== Dropwizard Metrics provides

NOTE: Different metric types: `Counter`, `Gauge`, `Meter`, `Timer`, ...

NOTE: Different reporter: JMX, console, SLF4J, CSV, servlet, ...

NOTE: `MetricRegistry` object which collects all your app metrics

NOTE: Annotations for AOP frameworks: `@Counted`, `@Timed`, ...

NOTE: ... but does not include integration with these frameworks

CAUTION: More at https://dropwizard.github.io/metrics


== !

[.statement]
Discover how we created CDI integration module for Metrics


[.topic.source]
== Metrics out of the box (without CDI)
[source, subs="verbatim,quotes", role="smaller"]
----
class MetricsHelper {
    public static MetricRegistry REGISTRY = new MetricRegistry();
}
----

[source, subs="verbatim,quotes", role="smaller"]
----
class TimedMethodClass {

    void timedMethod() {
        Timer timer = MetricsHelper.REGISTRY.[highlight]#timer("timer")#; <1>
        Timer.Context time = timer.time();
        try {
            /\*...*/
        } finally {
            time.stop();
        }
    }
}
----
<1> Note that if a `Timer` named `"timer"` doesn't exist, `MetricRegistry` will create a default one and register it


[.topic.source]
== Basic CDI integration

[source, subs="verbatim,quotes", role="smaller"]
----
class MetricRegistryBean {
    [highlight]#@Produces#
    [highlight]#@ApplicationScoped#
    MetricRegistry registry = new MetricRegistry();
}

class TimedMethodBean {
    [highlight]#@Inject# MetricRegistry registry;

    void timedMethod() {
        Timer timer = registry.timer("timer");
        Timer.Context time = timer.time();
        try {
            /\*...*/
        } finally {
            time.stop();
        }
    }
}
----

TIP: We could have a lot more with advanced *CDI* features


[.topic]
== Our goals to achieve full CDI integration

[.statement]
====
CAUTION: Produce and inject multiple *metrics* of the same type


CAUTION: Enable Metrics with the provided annotations


CAUTION: Access same *`Metric`* instances through `@inject` or `MetricRegistry` API


//CAUTION: Automatically produce injected *Metrics* not produced (bonus)
====


[.topic]
== !

[.statement]
====
*GOAL 1* Produce and inject +
_multiple_ metrics of the same type
====


[.source]
== What's the problem with multiple Metrics of the same type?

WARNING: This code throws a deployment exception (ambiguous dependency)

[source, subs="verbatim,quotes"]
----
*@Produces*
Timer timer = new Timer(new SlidingTimeWindowReservoir(1L, MINUTES)); <1>

*@Produces*
Timer timer = new Timer(new SlidingTimeWindowReservoir(1L, HOURS)); <2>

*@Inject*
Timer timer; <3>
----
<1> This timer that only keeps measurement of last minute is produced as a bean of type `Timer`
<2> This timer that only keeps measurement of last hour is produced as a bean of type `Timer`
<3> This injection point is ambiguous since 2 eligible beans exist


[.source]
== Solving the ambiguity

TIP: We could use the provided `@Metric` annotation to qualify our beans

[source, subs="verbatim,quotes"]
----
*@Produces*
[highlight]*@Metric(name = "myTimer")*
Timer timer = new Timer(new SlidingTimeWindowReservoir(1L, MINUTES));

*@Produces*
[highlight]*@Metric(name = "mySecondTimer")*
Timer timer = new Timer(new SlidingTimeWindowReservoir(1L, HOURS));

*@Inject*
[highlight]*@Metric(name = "myTimer")*
Timer timer;
----

CAUTION: That won't work out of the box since `@Metric` is not a qualifier


[.source]
== How to make `@Metric` a qualifier?

TIP: By observing `BeforeBeanDiscovery` lifecycle event in an extension

[source, subs="verbatim,quotes", role="smaller"]
----
public interface BeforeBeanDiscovery {

    [highlight]#addQualifier(Class<? extends Annotation> qualifier);#  <1>
    addQualifier(AnnotatedType<? extends Annotation> qualifier);
    addScope(Class<? extends Annotation> scopeType, boolean normal, boolean passivation);
    addStereotype(Class<? extends Annotation> stereotype, Annotation... stereotypeDef);
    addInterceptorBinding(AnnotatedType<? extends Annotation> bindingType);
    addInterceptorBinding(Class<? extends Annotation> bindingType, Annotation... bindingTypeDef);
    addAnnotatedType(AnnotatedType<?> type);
    addAnnotatedType(AnnotatedType<?> type, String id);
}
----
<1> The method we need to declare the `@Metric` annotation as a CDI qualifier

TIP: And use `addQualifier()` method in the event


[.topic.source]
== `BeforeBeanDiscovery` is first in lifecycle

[plantuml, "lifecycle-BBD", "svg", height="85%", width="95%"]
----
@startuml

skinparam shadowing false
skinparam backgroundColor transparent
skinparam defaultFontName Consolas

skinparam activity {
  FontSize 20
  FontName Consolas
  FontColor #337788
  ArrowColor #888888
  BorderColor #337788
  BackgroundColor #white

  FontColor<< Internal >> #888888
  BorderColor<< Internal >> #888888
  BackgroundColor<< Internal >> #white

  FontColor<< Once >> #BB3322
  BorderColor<< Once >> #BB3322
  BackgroundColor<< Once >> #white

  FontColor<< Highlight >> white
  BorderColor<< Highlight >> #337788
  BackgroundColor<< Highlight >> #337788

  FontColor<< Highlightonce >> white
  BorderColor<< Highlightonce >> #BB3322
  BackgroundColor<< Highlightonce >> #BB3322
}

(*) -right-> "Deployment\nStart" << Internal >>
-right-> "Before\nBean\nDiscovery" <<Highlightonce>>
-right-> "Scan\nArchive" << Internal >>
-right-> "Process\nAnnotated\nType"
-right-> "After\nType\nDiscovery" << Once >>
-down-> "Bean\nEligibility\nCheck" << Internal >>
-left-> "Process\nInjection\nPoint"
-left-> "Process\nInjection\nTarget"
-left-> "Process\nBean\nAttributes"
-down-> "Process\nBean"
-right-> "Process\nProducer"
-right-> "Process\nObserver\nMethod"
-right-> "After\nBean\nDiscovery" << Once >>
-down-> "After\nDeployment\nValidation" << Once >>
-left-> "Application\nRunning" << Internal >>
-left-> "Before\nShutdown" << Once >>
-left-> "Undeploy\nApplication" << Internal >>
-left-> (*)

@enduml
----

include::legend.adoc[]


[.source]
== Our first extension

TIP: A CDI extension is a class implementing the `Extension` tag interface

.`org.cdi.further.metrics.MetricsExtension`
[source, subs="verbatim,quotes"]
----
public class MetricsExtension implements [highlight]*Extension* {

    void addMetricAsQualifier(*@Observes* BeforeBeanDiscovery bdd) {
        bdd.addQualifier(Metric.class);
    }
}
----

TIP: Extension is activated by adding this file to `META-INF/services`

.`javax.enterprise.inject.spi.Extension`
[source, subs="verbatim,quotes"]
----
org.cdi.further.metrics.MetricsExtension
----


[.topic]
== Goal 1 achieved

TIP: We can now write:

[source, subs="verbatim,quotes"]
----
*@Produces*
[highlight]*@Metric(name = "myTimer")*
Timer timer = new Timer(new SlidingTimeWindowReservoir(1L, MINUTES));

*@Produces*
[highlight]*@Metric(name = "mySecondTimer")*
Timer timer = new Timer(new SlidingTimeWindowReservoir(1L, HOURS));

*@Inject*
[highlight]*@Metric(name = "myTimer")*
Timer timer;
----

TIP: And have the `Timer` injection points satisfied


[.topic]
== !

[.statement]
====
*GOAL 2* Apply Metrics with the provided annotations
====

[.topic]
== Goal 2 in detail

TIP: We want to be able to write:

[source, subs="verbatim,quotes"]
----
[highlight]#@Timed#("timer") <1>
void timedMethod() {
    //...
}
----

TIP: And have the _timer_ `"timer"` activated during method invocation

CAUTION: The solution is to declare an interceptor and bind it to `@Timed`


[.topic]
== Goal 2 step by step

[.statement]
====
TIP: Create an interceptor for the timer's _technical code_

TIP: Make `@Timed` (provided by Metrics) a valid interceptor binding

TIP: Programmatically add `@Timed` as an interceptor binding

icon:magic[]
====


[.topic.source]
== Preparing interceptor creation

TIP: We should find the _technical code_ that will wrap the _business code_

[source, subs="verbatim,quotes"]
----
class TimedMethodBean {

    [highlight]#@Inject MetricRegistry registry;#

    void timedMethod() {
        [highlight]#Timer timer = registry.timer("timer");#
        [highlight]#Timer.Context time = timer.time();#
        [highlight]#try {#
            // Business code
        [highlight]#} finally {#
            [highlight]#time.stop();#
        [highlight]#}#
    }
}
----


[.topic.source]
== Creating the interceptor
TIP: Interceptor code is highlighted below

[source, subs="verbatim,quotes", role="smaller"]
----
[highlight]*@Interceptor*
class TimedInterceptor {
    @Inject MetricRegistry registry; <1>
    [highlight]*@AroundInvoke*
    Object timedMethod([highlight]_InvocationContext_ context) throws Exception {
        Timer timer = registry.timer(context.getMethod().getAnnotation(Timed.class).name());
        Timer.Context time = timer.time();
        try {
            return [highlight]_context.proceed()_; <2>
        } finally {
            time.stop();
        }
    }
}
----
<1> In CDI an interceptor is a bean, you can inject other beans in it
<2> Here the *business* of the application is called. All the code around is the *technical* one.


[.topic.source]
== Activating the interceptor

[source, subs="verbatim,quotes", role="smaller"]
----
@Interceptor
[highlight]*@Priority(Interceptor.Priority.LIBRARY_BEFORE)*  <1>
class TimedInterceptor {

    @Inject
    MetricRegistry registry;

    @AroundInvoke
    Object timedMethod(InvocationContext context) throws Exception {
        Timer timer = registry.timer(context.getMethod().getAnnotation(Timed.class).name());
        Timer.Context time = timer.time();
        try {
            return context.proceed();
        } finally {
            time.stop();
        }
    }
}
----
<1> Giving a `@Priority` to an interceptor _activates_ and _orders_ it


[.topic.source]
== Add a binding to the interceptor

[source, subs="verbatim,quotes", role="smaller"]
----
[highlight]#@Timed#  <1>
@Interceptor
@Priority(Interceptor.Priority.LIBRARY_BEFORE)
class TimedInterceptor {

    @Inject
    MetricRegistry registry;

    @AroundInvoke
    Object timedMethod(InvocationContext context) throws Exception {
        Timer timer = registry.timer(context.getMethod().getAnnotation(Timed.class).name());
        Timer.Context time = timer.time();
        try {
            return context.proceed();
        } finally {
            time.stop();
        }
    }
}
----
<1> We'll use Metrics `@Timed` annotation as interceptor binding


[.topic.source]
== Back on interceptor binding
TIP: An *interceptor binding* is an annotation used in 2 places:

. On the *interceptor class* to bind it to this annotation
. On the *methods* or *classes* to be intercepted by this interceptor

TIP: An interceptor binding should have the `@InterceptorBinding` annotation or should be declared programmatically

TIP: If the interceptor binding annotation has members:

. Their values are *taken into account* to resolve interceptor
. Unless members are annotated with `@NonBinding`


[.topic.source]
== `@Timed` source code is not an interceptor binding

[source, subs="verbatim,quotes"]
----
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target({ ElementType.TYPE, ElementType.CONSTRUCTOR, ElementType.METHOD, ElementType.ANNOTATION_TYPE }) <1>
public @interface Timed {

    String name() default ""; <2>

    boolean absolute() default false; <2>
}
----
<1> Lack the `@InterceptorBinding` annotation
<2> None of the members have the `@NonBinding` annotation, so `@Timed(name = "timer1")` and `@Timed(name = "timer2")` will be 2 different interceptor bindings


[.topic.source]
== The required `@Timed` source code to make it an interceptor binding

[source, subs="verbatim,quotes"]
----
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target({ ElementType.TYPE, ElementType.CONSTRUCTOR, ElementType.METHOD, ElementType.ANNOTATION_TYPE })
[highlight]#@InterceptorBinding#
public @interface Timed {

    [highlight]#@NonBinding# String name() default "";

    [highlight]#@NonBinding# boolean absolute() default false;
}
----

icon:question-circle[] How to achieve the required `@Timed` declaration?

icon:ban[] We cannot touch the component source / binary!


[.topic.source]
== Using the `AnnotatedType` SPI

TIP: Thanks to _DeltaSpike_ we can easily create the required `AnnotatedType`

[source, subs="verbatim,quotes"]
----
AnnotatedType createTimedAnnotatedType() throws Exception {
    Annotation nonBinding = new AnnotationLiteral<Nonbinding>() {}; <1>
    return new AnnotatedTypeBuilder().readFromType(Timed.class) <2>
        .addToMethod(Timed.class.getMethod("name"), nonBinding) <3>
        .addToMethod(Timed.class.getMethod("absolute"), nonBinding) <3>
        .create();
}
----
<1> This creates an instance of `@NonBinding` annotation
<2> It would have been possible but far more verbose to create this `AnnotatedType` without the help of DeltaSpike. The `AnnotatedTypeBuilder` is initialized from the Metrics `@Timed` annotation.
<3> `@NonBinding` is added to both members of the `@Timed` annotation


[.topic.source]
== This extension will do the job

TIP: We observe `BeforeBeanDiscovery` to add a new interceptor binding

[source, subs="verbatim,quotes"]
----
public class MetricsExtension implements Extension {

    void addTimedBinding(*@Observes* BeforeBeanDiscovery bdd) throws Exception {
        Annotation nonBinding = new AnnotationLiteral<Nonbinding>() {};

        bdd.addInterceptorBinding(new AnnotatedTypeBuilder<Timed>()
            .readFromType(Timed.class)
            .addToMethod(Timed.class.getMethod("name"), nonBinding)
            .addToMethod(Timed.class.getMethod("absolute"), nonBinding)
            .create());
    }
}
----


[.topic]
== Goal 2 achieved

[.statement]
====
TIP: We can now write:

[source, subs="verbatim,quotes"]
----
@Timed("timer")
void timedMethod() {
    // Business code
}
----

And have a Metrics `Timer` applied to the method

[none]
. icon:code-fork[] Interceptor code should be enhanced to support `@Timed` on classes
. icon:code-fork[] Other interceptors should be developed for other metric types
====


[.topic.source]
== Our goals

. Apply a metric with the provided annotation in AOP style
+
[source, subs="verbatim,quotes", role="smallest"]
----
[highlight]#@Timed#("timer") <1>
void timedMethod() {
    //...
}
----

. Register automatically produced custom metrics
+
[source, subs="verbatim,quotes", role="smallest"]
----
@Produces
[highlight]#@Metric#(name = "myTimer") <1>
Timer timer = new Timer(new SlidingTimeWindowReservoir(1L, MINUTES));
//...
[highlight]#@Timed#("myTimer") <1>
void timedMethod() { /\*...*/ }
----
<1> Annotations provided by Metrics


[.topic]
== !

[.statement]
====
*GOAL 3* Access same *`Metric`* instances through `@Inject` or `MetricRegistry` API
====


[.topic]
== Goal 3 in detail

TIP: When writing:

[source, subs="verbatim,quotes"]
----
@Inject
@Metric(name = "myTimer")
Timer [highlight]*timer1*;

@Inject
MetricRegistry registry;

Timer [highlight]*timer2* = registry.timer("myTimer");
----

TIP: ... We want that `timer1 == timer2`


[.topic.source]
== Goal 3 in detail

[source, subs="verbatim,quotes", role="smaller"]
----
@Produces
@Metric(name = "myTimer") <1>
Timer [highlight]*timer* = new Timer(new SlidingTimeWindowReservoir(1L, TimeUnit.MINUTES));

@Inject
@Metric(name = "myTimer")
Timer [highlight]*timer*;

@Inject
MetricRegistry registry;

Timer [highlight]*timer* = registry.timer("myTimer"); <2>
----
<1> Produced `Timer` should be added to MetricRegistry when produced
<2> When retrieved from registry, a `Metric` should be *identical* to the produced instance and vice versa

WARNING: There are 2 `Metric` classes, the `com.codahale.metrics.Metric` interface and the `com.codahale.metrics.annotation.Metric` annotation


[.topic.source]
== Goal 3 step by step

TIP: We need to write an extension that will:

. Change how a `Metric` instance is produced by looking it up in the registry first and producing (and registering) it only if it's not found. We'll do this by:
.. observing the `ProcessProducer` lifecycle event
.. decorating Metric `Producer` to add this new behavior
. Produce all `Metric` instances at the end of bootstrap to have them in registry for runtime
.. we'll do this by observing `AfterDeploymentValidation` event


[.topic.source]
== So we will `@Observes` these 2 events to add our features

[plantuml, "lifecycle-BBD-PP-ADV", "svg", height="85%", width="95%"]
----
@startuml

skinparam shadowing false
skinparam backgroundColor transparent
skinparam defaultFontName Consolas

skinparam activity {
  FontSize 20
  FontName Consolas
  FontColor #337788
  ArrowColor #888888
  BorderColor #337788
  BackgroundColor #white

  FontColor<< Internal >> #888888
  BorderColor<< Internal >> #888888
  BackgroundColor<< Internal >> #white

  FontColor<< Once >> #BB3322
  BorderColor<< Once >> #BB3322
  BackgroundColor<< Once >> #white

  FontColor<< Highlight >> white
  BorderColor<< Highlight >> #337788
  BackgroundColor<< Highlight >> #337788

  FontColor<< Highlightonce >> white
  BorderColor<< Highlightonce >> #BB3322
  BackgroundColor<< Highlightonce >> #BB3322
}

(*) -right-> "Deployment\nStart" << Internal >>
-right-> "Before\nBean\nDiscovery" << Once >>
-right-> "Scan\nArchive" << Internal >>
-right-> "Process\nAnnotated\nType"
-right-> "After\nType\nDiscovery" << Once >>
-down-> "Bean\nEligibility\nCheck" << Internal >>
-left-> "Process\nInjection\nPoint"
-left-> "Process\nInjection\nTarget"
-left-> "Process\nBean\nAttributes"
-down-> "Process\nBean"
-right-> "Process\nProducer" <<Highlight>>
-right-> "Process\nObserver\nMethod"
-right-> "After\nBean\nDiscovery" << Once >>
-down-> "After\nDeployment\nValidation" <<Highlightonce>>
-left-> "Application\nRunning" << Internal >>
-left-> "Before\nShutdown" << Once >>
-left-> "Undeploy\nApplication" << Internal >>
-left-> (*)

@enduml
----

include::legend.adoc[]


[.topic.source]
== Customizing `Metric` producing process

NOTE: We first need to create our implementation of the `Producer<X>` SPI

[source, subs="verbatim,quotes"]
----
class MetricProducer<X extends Metric> implements Producer<X> {

    final Producer<X> decorate;

    final String metricName;

    MetricProducer(Producer<X> decorate, String metricName) {
        this.decorate = decorate;
        this.metricName = metricName;
    }

    //...
----


[.topic.source]
== Customizing `Metric` producing process (continued)

[source, subs="verbatim,quotes", role="smaller"]
----
    //...
    public X produce(CreationalContext<X> ctx) { <1>
        MetricRegistry reg = BeanProvider.getContextualReference(MetricRegistry.class, false); <2>
        if (!reg.getMetrics().containsKey(metricName)) <3>
            reg.register(metricName, [highlight]*decorate.produce(ctx)*);

        return (X) reg.getMetrics().get(metricName);
    }

    public void dispose(X instance) { }

    public Set<InjectionPoint> getInjectionPoints() {
        return decorate.getInjectionPoints();
    }
}
----
<1> Produce method will be used by the container at runtime to decorate declared producer with our logic
<2> `BeanProvider` is a DeltaSpike helper class to easily retrieve a bean or bean instance
<3> If metric name is not in the registry, the original producer is called and its result is added to the registry


[.topic.source]
== We'll use our `MetricProducer` in a `ProcessProducer` observer

NOTE: This event allow us to substitute the original producer with ours

[source, subs="verbatim,quotes"]
----
public interface ProcessProducer<T, X> {

    AnnotatedMember<T> getAnnotatedMember(); <1>

    Producer<X> getProducer(); <2>

    void setProducer(Producer<X> producer); <3>

    void addDefinitionError(Throwable t);
}
----
<1> Gets the `AnnotatedMember` associated to the `@Produces` field or method
<2> Gets the default producer (useful to decorate it)
<3> Overrides the producer


[.topic.source]
== Customizing `Metric` producing process (end)

TIP: Here's the extension code to do this producer decoration

[source, subs="verbatim,quotes", role="smaller"]
----
public class MetricsExtension implements Extension {
    //...
    <X extends Metric> void decorateMetricProducer([highlight]*@Observes* ProcessProducer<?, X> pp) {
        String name = pp.getAnnotatedMember().getAnnotation(Metric.class).name(); <1>
        pp.setProducer(new [highlight]#MetricProducer<>#([highlight]*pp.getProducer()*, name)); <2>
    }
    //...
}
----
<1> We retrieve metric name from the `name()` member in `@Metric`
<2> We replace the original producer by our producer (which decorates the former)


[.topic.source]
== Producing all the `Metric` instances at the end of boot time

[.statement]
====
NOTE: We do that by observing the `AfterDeploymentValidation` event

[source, subs="verbatim,quotes", role="smaller"]
----
public class MetricsExtension implements Extension {
    //...
    void registerProducedMetrics([highlight]*@Observes* AfterDeploymentValidation adv) {
        List<Metric> metrics = BeanProvider.getContextualReferences(Metric.class, true); <1>
    }
    //...
}
----
<1> `getContextualReferences()` is a method from *DeltaSpike* `BeanProvider` helper class. +
It creates the list of bean instances for a given bean type (ignoring qualifiers).
====


[.topic]
== Goal 3 achieved

[.statement]
====
TIP: We can now write:

[source, subs="verbatim,quotes"]
----
@Produces
@Metric(name = "myTimer")
Timer timer = new Timer(new SlidingTimeWindowReservoir(1L, MINUTES));

@Inject
MetricRegistry registry;

@Inject
@Metric("myTimer")
Metric timer;
----

TIP: And be sure that `registry.getMetrics().get("myTimer")` and `timer` are the same object (our custom `Timer`)
====


[.topic.source]
== Complete extension code

[source, subs="verbatim,quotes", role="smallest"]
----
public class MetricsExtension implements Extension {

    void addMetricAsQualifier(@Observes BeforeBeanDiscovery bdd) {bdd.addQualifier(Metric.class);}

    void addTimedBinding(@Observes BeforeBeanDiscovery bdd) throws Exception {
        Annotation nonBinding = new AnnotationLiteral<Nonbinding>() {};
        bdd.addInterceptorBinding(new AnnotatedTypeBuilder<Timed>().readFromType(Timed.class)
            .addToMethod(Timed.class.getMethod("name"), nonBinding)
            .addToMethod(Timed.class.getMethod("absolute"),nonBinding).create());
    }

    <T extends com.codahale.metrics.Metric> void decorateMetricProducer(@Observes ProcessProducer<?, T> pp) {
        if (pp.getAnnotatedMember().isAnnotationPresent(Metric.class)) {
            String name = pp.getAnnotatedMember().getAnnotation(Metric.class).name();
            pp.setProducer(new MetricProducer(pp.getProducer(), name));
        }
    }

    void registerProducedMetrics(@Observes AfterDeploymentValidation adv) {
        List<com.codahale.metrics.Metric> metrics = BeanProvider
            .getContextualReferences(com.codahale.metrics.Metric.class, true);
    }
}
----
