= Going further with CDI

image::https://travis-ci.org/astefanutti/further-cdi.svg[Travis CI build, link="https://travis-ci.org/astefanutti/further-cdi"]

Presentation material about advanced features and use cases of http://www.cdi-spec.org/[CDI], the Contexts and Dependency Injection standard for the Java platform.

== About

This presentation introduces the CDI type and metadata SPI. It then focuses on the concept of http://docs.jboss.org/cdi/spec/1.2/cdi-spec.html#spi[portable extensions] and covers the complete bean manager lifecycle, depicted in the diagram below. Lastly, it illustrates the use of these concepts through practical examples like the https://github.com/astefanutti/camel-cdi[Camel CDI] and https://github.com/astefanutti/metrics-cdi[Metrics CDI] extensions.

image::http://astefanutti.github.io/further-cdi/lifecycle.svg[]

== Presentation history

|===

| Conference | Session | Commit [/ Branch]  | Slides

| http://www.devoxx.fr/[Devoxx FR] 2015 | http://cfp.devoxx.fr/2015/talk/OGT-5265/Allons_plus_loin_avec_CDI_1.2[Allons plus loin avec CDI 1.2 [OGT-5265\]] | link:tree/b490b41747b70b0e5a28f05ba3e5ef20ec5dcd3c[`b490b41`] | http://astefanutti.github.io/further-cdi/going-further-with-cdi-devoxxfr-2015.html[html], http://astefanutti.github.io/further-cdi/going-further-with-cdi-devoxxfr-2015.pdf[pdf]
| http://www.devoxx.be/[Devoxx BE] 2014 | http://cfp.devoxx.be/2014/talk/CSX-3476/Going_farther_with_CDI_1.2[Going Further with CDI 1.2 [CSX-3476\]] | link:tree/6aa51e7230cd5177ab30135c21b0d17b428565e9[`6aa51e7`] | http://astefanutti.github.io/further-cdi/going-further-with-cdi-devoxxbe-2014.html[html]
| https://www.oracle.com/javaone/[JavaOne] 2014 | https://oracleus.activeevents.com/2014/connect/sessionDetail.ww?SESSION_ID=5585[Going Further with CDI 1.2 [CON5585\]] | link:tree/6fd80dd792e325729b6b8724f50b93475d5dc3be[`6fd80dd`] / link:tree/javaone[`javaone`] | http://astefanutti.github.io/further-cdi/going-further-with-cdi-javaone-2014.html[html]

|===

== Build environment

Install http://bundler.io/[Bundler]:
----
gem install bundler
----

Then run:
----
bundle install
----

Install http://www.graphviz.org/[Graphviz] and have the `dot` executable in the path.

== Build instructions

To generate the HTML presentation, run the following command:
----
asciidoctor -r asciidoctor-diagram -T asciidoctor-backends/slim -a data-uri -a linkcss! slides.adoc
----

Note that the Git submodules must first be initialized by running:
----
git submodule init
----
Followed with:
----
git submodule update
----

== Use Guard and LiveReload

With http://guardgem.org/[Guard] and http://livereload.com/[LiveReload], you can change the content of the doc and have the files automatically generated and your browser updated.

To start, make sure that you have all the needed gems installed:
----
bundle update
----

Then install the http://feedback.livereload.com/knowledgebase/articles/86242-how-do-i-install-and-use-the-browser-extensions-[LiveReload plugin] for your browser (Chrome, Firefox and Safari are supported).

Finally, launch Guard:
----
bundle exec guard
----

Browse to the generated file you want to refresh and activate the LiveReload plugin (don't forget to configure the plugin to accept refreshing local files).

== License

The content of this project is licensed under the http://creativecommons.org/licenses/by/4.0/[Creative Commons Attribution 4.0 license], and the underlying source code used for the examples is licensed under the http://opensource.org/licenses/mit-license.php[MIT license].
